/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.filteringDataBangunan;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class pageMenu extends javax.swing.JFrame {

    /**
     * Creates new form pageMenu
     */
    public pageMenu() {
        initComponents();
        pageTambahData page = new pageTambahData();
        
        deskPaneKonten.add(page);
        page.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBacktracking = new javax.swing.JPanel();
        txtBacktracking = new javax.swing.JLabel();
        btnTambahData = new javax.swing.JPanel();
        txtTambahData = new javax.swing.JLabel();
        btnBruteForce = new javax.swing.JPanel();
        txtBruteforce = new javax.swing.JLabel();
        deskPaneKonten = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 103, 138));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(154, 235, 163));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 253, 186));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Strategis Algoritma");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 30));

        jLabel2.setBackground(new java.awt.Color(154, 235, 163));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(218, 253, 186));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tugas Besar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 30));

        btnBacktracking.setBackground(new java.awt.Color(69, 196, 176));
        btnBacktracking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBacktrackingMouseClicked(evt);
            }
        });
        btnBacktracking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBacktracking.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBacktracking.setForeground(new java.awt.Color(1, 32, 48));
        txtBacktracking.setText("Backtracking");
        btnBacktracking.add(txtBacktracking, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(btnBacktracking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 60));

        btnTambahData.setBackground(new java.awt.Color(218, 253, 186));
        btnTambahData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahDataMouseClicked(evt);
            }
        });
        btnTambahData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTambahData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTambahData.setForeground(new java.awt.Color(1, 32, 48));
        txtTambahData.setText("Tambah Data");
        btnTambahData.add(txtTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(btnTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 60));

        btnBruteForce.setBackground(new java.awt.Color(69, 196, 176));
        btnBruteForce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBruteForceMouseClicked(evt);
            }
        });
        btnBruteForce.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBruteforce.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBruteforce.setForeground(new java.awt.Color(1, 32, 48));
        txtBruteforce.setText("Brute Force");
        btnBruteForce.add(txtBruteforce, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(btnBruteForce, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 190, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 700));

        javax.swing.GroupLayout deskPaneKontenLayout = new javax.swing.GroupLayout(deskPaneKonten);
        deskPaneKonten.setLayout(deskPaneKontenLayout);
        deskPaneKontenLayout.setHorizontalGroup(
            deskPaneKontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        deskPaneKontenLayout.setVerticalGroup(
            deskPaneKontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(deskPaneKonten, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 910, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBacktrackingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBacktrackingMouseClicked
        // TODO add your handling code here:
        
        pageBacktracking page = new pageBacktracking();
        deskPaneKonten.add(page).setVisible(true);
        
        btnBacktracking.setBackground(new java.awt.Color(218,253,186));
        btnBruteForce.setBackground(new java.awt.Color(69,196,176));
        btnTambahData.setBackground(new java.awt.Color(69,196,176));
        
    }//GEN-LAST:event_btnBacktrackingMouseClicked

    private void btnTambahDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahDataMouseClicked
        // TODO add your handling code here:
        pageTambahData page = new pageTambahData();
        deskPaneKonten.add(page).setVisible(true);

        btnTambahData.setBackground(new java.awt.Color(218,253,186));
        btnBruteForce.setBackground(new java.awt.Color(69,196,176));
        btnBacktracking.setBackground(new java.awt.Color(69,196,176));

    }//GEN-LAST:event_btnTambahDataMouseClicked

    private void btnBruteForceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBruteForceMouseClicked
        // TODO add your handling code here:
        pageBruteforce page = new pageBruteforce();
        deskPaneKonten.add(page).setVisible(true);
        
        btnBruteForce.setBackground(new java.awt.Color(218,253,186));
        btnTambahData.setBackground(new java.awt.Color(69,196,176));
        btnBacktracking.setBackground(new java.awt.Color(69,196,176));
        
    }//GEN-LAST:event_btnBruteForceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBacktracking;
    private javax.swing.JPanel btnBruteForce;
    private javax.swing.JPanel btnTambahData;
    private javax.swing.JDesktopPane deskPaneKonten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtBacktracking;
    private javax.swing.JLabel txtBruteforce;
    private javax.swing.JLabel txtTambahData;
    // End of variables declaration//GEN-END:variables
}
