/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.filteringDataBangunan;
import java.awt.Font;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author David
 */
public class pageTambahData extends javax.swing.JInternalFrame {

    /**
     * Creates new form pageTambahData
     */
    public void setDataTable(){
        DefaultTableModel tableModel = (DefaultTableModel) tblDataBarang.getModel();
        tokoBangunan toko = new tokoBangunan();
        tblDataBarang.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        for(int i = 0; i < toko.getTokoBangunan().size(); i++){
            String nama = toko.getDataBangunan(i).getBarang();
            String kategori = toko.getDataBangunan(i).getKategori();
            int harga = toko.getDataBangunan(i).getHarga();
            int kualitas = toko.getDataBangunan(i).getKualitas();
            
            Object[] data = {nama, kategori, harga, kualitas};
            
            tableModel.addRow(data);
        }
    }
    
    public pageTambahData() {
        initComponents();
        BasicInternalFrameUI title = (BasicInternalFrameUI) this.getUI();
        title.setNorthPane(null);
        
        setDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comboBoxKategoriBarang = new javax.swing.JComboBox<>();
        txtFieldHargaBarang = new javax.swing.JTextField();
        txtFieldNamaBarang = new javax.swing.JTextField();
        comboBoxToko = new javax.swing.JComboBox<>();
        comboBoxKualitasBarang = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        comboBoxShowToko = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataBarang = new javax.swing.JTable();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 103, 138));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 253, 186));
        jLabel1.setText("Tambah Data Barang Bangunan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data Bangunan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBoxKategoriBarang.setBackground(new java.awt.Color(240, 240, 240));
        comboBoxKategoriBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangunan", "Lantai", "Perekat", "Adonan", "Atap" }));
        comboBoxKategoriBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Kategori Barang"));
        jPanel2.add(comboBoxKategoriBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 150, 40));

        txtFieldHargaBarang.setBackground(new java.awt.Color(240, 240, 240));
        txtFieldHargaBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Harga Barang", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.add(txtFieldHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 40));

        txtFieldNamaBarang.setBackground(new java.awt.Color(240, 240, 240));
        txtFieldNamaBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Nama Barang", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.add(txtFieldNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 40));

        comboBoxToko.setBackground(new java.awt.Color(240, 240, 240));
        comboBoxToko.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toko A", "Toko B", "Toko C" }));
        comboBoxToko.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Toko Bangunan"));
        jPanel2.add(comboBoxToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 130, 40));

        comboBoxKualitasBarang.setBackground(new java.awt.Color(240, 240, 240));
        comboBoxKualitasBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        comboBoxKualitasBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Kualitas Barang"));
        jPanel2.add(comboBoxKualitasBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 150, 40));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 130, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 550, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Data Bangunan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBoxShowToko.setBackground(new java.awt.Color(240, 240, 240));
        comboBoxShowToko.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toko A", "Toko B", "Toko C" }));
        comboBoxShowToko.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Toko Bangunan"));
        jPanel4.add(comboBoxShowToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 40));

        tblDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Kategori Barang", "Harga Barang", "Kualitas Barang"
            }
        ));
        tblDataBarang.setEnabled(false);
        jScrollPane1.setViewportView(tblDataBarang);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 17, 730, 410));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 890, 440));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        if(txtFieldHargaBarang.getText() != "" || txtFieldNamaBarang.getText() != ""){
            String namaBarang = txtFieldNamaBarang.getText();
            String kategoriBarang = (String) comboBoxKategoriBarang.getSelectedItem();
            int hargaBarang = Integer.parseInt(txtFieldHargaBarang.getText());
            int kualitasBarang = Integer.valueOf((String) comboBoxKualitasBarang.getSelectedItem());

            if(comboBoxToko.getSelectedIndex() == 0){
                tokoBangunan toko = new tokoBangunan();
                dataBangunan data = new dataBangunan();
                DefaultTableModel model = (DefaultTableModel) tblDataBarang.getModel();
                
                data = data.setDataBarang(namaBarang, kategoriBarang, hargaBarang, kualitasBarang);
                
                toko.addDataBangunan(data);
                
                switch(comboBoxKategoriBarang.getSelectedIndex()){
                    case 0:
                        toko.addJenisBangunan(data);
                        break;
                    case 1:
                        toko.addJenisLantai(data);
                        break;
                    case 2:
                        toko.addJenisPerekat(data);
                        break;
                    case 3:
                        toko.addJenisAdonan(data);
                        break;
                    case 4:
                        toko.addJenisAtap(data);
                        break;
                }
                
                model.setRowCount(0);
                setDataTable();
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> comboBoxKategoriBarang;
    private javax.swing.JComboBox<String> comboBoxKualitasBarang;
    private javax.swing.JComboBox<String> comboBoxShowToko;
    private javax.swing.JComboBox<String> comboBoxToko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDataBarang;
    private javax.swing.JTextField txtFieldHargaBarang;
    private javax.swing.JTextField txtFieldNamaBarang;
    // End of variables declaration//GEN-END:variables
}
