/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.bruteForceMethod;
import controller.filteringDataBangunan;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.tokoBangunan;

/**
 *
 * @author David
 */
public class pageBruteforce extends javax.swing.JInternalFrame {

    /**
     * Creates new form pageBruteforce
     */
    public pageBruteforce() {
        initComponents();
        BasicInternalFrameUI title = (BasicInternalFrameUI) this.getUI();
        title.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtFieldBudget = new javax.swing.JTextField();
        btnSolusi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFieldBanyakBangunan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldBanyakAtap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldBanyakLantai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFieldBanyakAdonan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFieldBanyakPerekat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboBoxToko = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasilBF = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JLabel();
        txtBangunan = new javax.swing.JLabel();
        txtAtap = new javax.swing.JLabel();
        txtLantai = new javax.swing.JLabel();
        txtAdonan = new javax.swing.JLabel();
        txtPerekat = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 103, 138));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 253, 186));
        jLabel1.setText("Metode Bruteforce");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pemilihan Pemakaian Bahan Bangunan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFieldBudget.setBackground(new java.awt.Color(240, 240, 240));
        txtFieldBudget.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Budget Client", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.add(txtFieldBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 130, 40));

        btnSolusi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSolusi.setText("Cari Solusi");
        btnSolusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolusiActionPerformed(evt);
            }
        });
        jPanel2.add(btnSolusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 130, 30));

        jLabel2.setText("Bahan Bangunan");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 40));
        jPanel2.add(txtFieldBanyakBangunan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 60, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("/ Bahan");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 50, 20));

        jLabel4.setText("Bahan Atap");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 40));
        jPanel2.add(txtFieldBanyakAtap, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("/ Bahan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 50, 20));
        jPanel2.add(txtFieldBanyakLantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 60, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("/ Bahan");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 50, 20));

        jLabel7.setText("Bahan Lantai");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 40));

        jLabel8.setText("Bahan Adonan");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 100, 40));
        jPanel2.add(txtFieldBanyakAdonan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 60, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("/kg");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 50, 20));

        jLabel10.setText("Toko Bangunan");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 100, 20));
        jPanel2.add(txtFieldBanyakPerekat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 60, 20));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("/kg");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 50, 20));

        comboBoxToko.setBackground(new java.awt.Color(240, 240, 240));
        comboBoxToko.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toko A", "Toko B", "Toko C" }));
        comboBoxToko.setBorder(null);
        jPanel2.add(comboBoxToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 90, 20));

        jLabel12.setText("Bahan Perekat");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 100, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 600, 150));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Solusi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHasilBF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblHasilBF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bangunan / KB", "Adonan / KB", "Perekat / KB", "Lantai / KB", "Atap / KB", "Total harga"
            }
        ));
        jScrollPane1.setViewportView(tblHasilBF);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 860, 390));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 890, 430));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Solusi Terbaik"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Harga"));
        jPanel5.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 132, 41));

        txtBangunan.setBorder(javax.swing.BorderFactory.createTitledBorder("Bangunan"));
        jPanel5.add(txtBangunan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 132, 41));

        txtAtap.setBorder(javax.swing.BorderFactory.createTitledBorder("Atap"));
        jPanel5.add(txtAtap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 132, 41));

        txtLantai.setBorder(javax.swing.BorderFactory.createTitledBorder("Lantai"));
        jPanel5.add(txtLantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 132, 41));

        txtAdonan.setBorder(javax.swing.BorderFactory.createTitledBorder("Adonan"));
        jPanel5.add(txtAdonan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 132, 41));

        txtPerekat.setBorder(javax.swing.BorderFactory.createTitledBorder("Perekat"));
        jPanel5.add(txtPerekat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 132, 41));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 290, 150));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolusiActionPerformed
        // TODO add your handling code here:
        bruteForceMethod bf = new bruteForceMethod();
        tokoBangunan toko = new tokoBangunan();
        
        int bahanBangunan = Integer.parseInt(txtFieldBanyakBangunan.getText());
        int bahanAtap = Integer.parseInt(txtFieldBanyakAtap.getText());
        int bahanAdonan = Integer.parseInt(txtFieldBanyakAdonan.getText());
        int bahanLantai = Integer.parseInt(txtFieldBanyakLantai.getText());
        int bahanPerekat = Integer.parseInt(txtFieldBanyakPerekat.getText());
        int budget = Integer.parseInt(txtFieldBudget.getText());
        
        bf.bruteForce(bahanBangunan, bahanAtap, bahanLantai, bahanAdonan, bahanPerekat, budget);
        
        txtBangunan.setText(toko.getSolusiData()[0]);
        txtAdonan.setText(toko.getSolusiData()[1]);
        txtPerekat.setText(toko.getSolusiData()[2]);
        txtLantai.setText(toko.getSolusiData()[3]);
        txtAtap.setText(toko.getSolusiData()[4]);
        txtTotal.setText(String.valueOf(toko.getSolusiHarga()));
    }//GEN-LAST:event_btnSolusiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolusi;
    private javax.swing.JComboBox<String> comboBoxToko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblHasilBF;
    private javax.swing.JLabel txtAdonan;
    private javax.swing.JLabel txtAtap;
    private javax.swing.JLabel txtBangunan;
    private javax.swing.JTextField txtFieldBanyakAdonan;
    private javax.swing.JTextField txtFieldBanyakAtap;
    private javax.swing.JTextField txtFieldBanyakBangunan;
    private javax.swing.JTextField txtFieldBanyakLantai;
    private javax.swing.JTextField txtFieldBanyakPerekat;
    private javax.swing.JTextField txtFieldBudget;
    private javax.swing.JLabel txtLantai;
    private javax.swing.JLabel txtPerekat;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
